import type { ExamLevel, ExamTrack } from "@prisma/client";

export type SeedSubject = {
  code: string;
  name: string;
  level: ExamLevel;
  tracks: ExamTrack[];
  order: number;
  topics: { name: string; level: ExamLevel; order: number }[];
};

// Curriculum derived from the existing Excel workbook + MEB YKS topic lists.
export const SEED_SUBJECTS: SeedSubject[] = [
  {
    code: "MAT1",
    name: "TYT Matematik",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 10,
    topics: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme - Bölünebilme",
      "EBOB-EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "1. Dereceden Denklem ve Eşitsizlikler",
      "Kümeler",
      "Fonksiyonlar",
      "Permütasyon - Kombinasyon",
      "Binom ve Olasılık",
      "İstatistik",
      "Asal Sayılar",
      "Tek-Çift ve Ardışık Sayılar",
      "Faktöriyel",
      "Mantık",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "PROB",
    name: "TYT Problemler",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 11,
    topics: [
      "Sayı - Kesir Problemleri",
      "Yaş Problemleri",
      "İşçi Problemleri",
      "Hız - Hareket Problemleri",
      "Yüzde Problemleri",
      "Kar - Zarar Problemleri",
      "Karışım Problemleri",
      "Faiz Problemleri",
      "Grafik Problemleri",
      "Sayısal Mantık Problemleri",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "GEO",
    name: "TYT Geometri",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 12,
    topics: [
      "Doğruda ve Üçgende Açılar",
      "Dik ve Özel Üçgenler",
      "İkizkenar ve Eşkenar Üçgen",
      "Üçgende Açıortay",
      "Üçgende Kenarortay",
      "Üçgende Eşlik ve Benzerlik",
      "Üçgende Alan",
      "Üçgende Açı-Kenar Bağıntıları",
      "Çokgenler",
      "Dörtgenler - Deltoid",
      "Paralelkenar - Eşkenar Dörtgen",
      "Dikdörtgen - Kare",
      "Yamuk",
      "Çemberde Açılar",
      "Çemberde Uzunluk",
      "Daire",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşümler",
      "Çemberin Analitiği",
      "Katı Cisimler",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "FIZ",
    name: "TYT Fizik",
    level: "TYT",
    tracks: ["SAYISAL", "EA"],
    order: 13,
    topics: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Özkütle - Dayanıklılık",
      "Basınç - Kaldırma Kuvveti",
      "Isı ve Sıcaklık - Genleşme",
      "Hareket - Kuvvet",
      "İş Güç Enerji",
      "Elektrostatik",
      "Elektrik Akımı - Ohm - Güç",
      "Manyetizma",
      "Dalgalar",
      "Optik",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "KIM",
    name: "TYT Kimya",
    level: "TYT",
    tracks: ["SAYISAL", "EA"],
    order: 14,
    topics: [
      "Kimya Bilimi",
      "Atomun Yapısı",
      "Periyodik Tablo",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları",
      "Mol Kavramı",
      "Kimyasal Tepkimelerde Hesaplamalar",
      "Karışımlar",
      "Asit - Baz - Tuz",
      "Kimya Her Yerde",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "BIY",
    name: "TYT Biyoloji",
    level: "TYT",
    tracks: ["SAYISAL", "EA"],
    order: 15,
    topics: [
      "Yaşam Bilimi Biyoloji",
      "Hücre - Madde Geçişi",
      "Hücre Organelleri",
      "Canlıların Sınıflandırılması",
      "Hücre Bölünmesi ve Üreme",
      "Kalıtım",
      "Ekosistem ve Ekoloji",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "TUR",
    name: "TYT Türkçe",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 16,
    topics: [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragrafın Yapısı",
      "Paragrafın Konu ve Ana Düşünce",
      "Paragrafın Yardımcı Düşüncesi",
      "Anlatım Biçimleri",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı",
      "Sözcük Türleri",
      "Edat - Bağlaç - Ünlem",
      "Eylemler",
      "Fiilde Çatı",
      "Ek Fiil",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozuklukları",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "TAR",
    name: "TYT Tarih",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 17,
    topics: [
      "Tarih Bilimi",
      "Uygarlığın Doğuşu - İlk Çağ",
      "İlk Türk Devletleri",
      "İslam Tarihi ve Uygarlığı",
      "Türk İslam Devletleri",
      "Beylikten Devlete Osmanlı",
      "Dünya Gücü Osmanlı",
      "Arayış Yılları",
      "Dağılma Dönemi",
      "20. Yüzyılda Osmanlı",
      "Kurtuluş Savaşı",
      "Atatürk Dönemi",
      "Çağdaş Türk ve Dünya Tarihi",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "COG",
    name: "TYT Coğrafya",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 18,
    topics: [
      "Doğa ve İnsan",
      "Harita Bilgisi",
      "Dünyanın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "İklim Bilgisi",
      "Yer Şekilleri",
      "Nüfus ve Yerleşme",
      "Türkiye'nin Fiziki Özellikleri",
      "Türkiye'nin Ekonomisi",
      "Türkiye'nin Yeryüzü Şekilleri",
      "Bölgeler ve Ülkeler",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "FEL",
    name: "TYT Felsefe",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 19,
    topics: [
      "Felsefeyi Tanıma",
      "Bilgi Felsefesi",
      "Bilim Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Psikoloji",
      "Sosyoloji",
      "Mantık",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  {
    code: "DIN",
    name: "TYT Din Kültürü",
    level: "TYT",
    tracks: ["SAYISAL", "EA", "SOZEL", "DIL"],
    order: 20,
    topics: [
      "Bilgi ve İnanç",
      "İslam ve İbadet",
      "Ahlak ve Değerler",
      "Din ve Hayat",
      "Hz. Muhammed'in Hayatı",
      "Kur'an ve Yorumu",
      "İslam Düşüncesi",
      "Dinler Tarihi",
    ].map((name, i) => ({ name, level: "TYT", order: i })),
  },
  // --- AYT ---
  {
    code: "AYT_MAT",
    name: "AYT Matematik",
    level: "AYT",
    tracks: ["SAYISAL", "EA"],
    order: 30,
    topics: [
      "Fonksiyonlar",
      "Polinomlar",
      "2. Dereceden Denklemler",
      "Eşitsizlikler",
      "Parabol",
      "Trigonometri 1",
      "Trigonometri 2",
      "Logaritma",
      "Diziler",
      "Limit",
      "Türev 1",
      "Türev 2",
      "İntegral 1",
      "İntegral 2",
      "Kümeler",
      "Sayma - Olasılık",
      "Karmaşık Sayılar",
      "Bileşke ve Ters Fonksiyon",
      "Üstel Fonksiyonlar",
      "Süreklilik",
      "Seriler",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_GEO",
    name: "AYT Geometri",
    level: "AYT",
    tracks: ["SAYISAL", "EA"],
    order: 31,
    topics: [
      "Katı Cisimler - Prizmalar",
      "Piramit",
      "Küre",
      "Dönel Cisimler",
      "Doğrunun Analitiği",
      "Dönüşümler",
      "Çemberin Analitiği",
      "Analitik Genel Tekrar",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_FIZ",
    name: "AYT Fizik",
    level: "AYT",
    tracks: ["SAYISAL"],
    order: 32,
    topics: [
      "Vektörler - Kuvvet",
      "Tork ve Denge",
      "Ağırlık ve Kütle Merkezi",
      "Basit Makinalar",
      "Doğrusal Hareket",
      "Newton Hareket Yasaları",
      "İş Güç Enerji",
      "Yeryüzünde Hareket",
      "İtme - Momentum",
      "Çembersel Hareket",
      "Açısal Momentum - Kepler",
      "Basit Harmonik Hareket",
      "Elektrik - Kuvvet Alan - Potansiyel",
      "Yüklü Parçacıklar - Sığaçlar",
      "Manyetizma",
      "İndüksiyon - Alternatif Akım - Transformatör",
      "Dalga Mekaniği",
      "Atom Fiziği - Radyoaktivite",
      "Modern Fizik",
      "Modern Fiziğin Uygulamaları",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_KIM",
    name: "AYT Kimya",
    level: "AYT",
    tracks: ["SAYISAL"],
    order: 33,
    topics: [
      "Modern Atom Teorisi",
      "Gazlar",
      "Çözeltiler",
      "Kimya ve Enerji (Entalpi)",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Tepkimelerde Denge",
      "Asit - Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimya ve Elektrik",
      "Karbon Kimyası",
      "Hidrokarbonlar (Alkan)",
      "Hidrokarbonlar (Alken)",
      "Hidrokarbonlar (Alkin)",
      "Fonksiyonel Gruplar (Alkol - Eter)",
      "Fonksiyonel Gruplar (Aldehit - Keton - Ester)",
      "Enerji Kaynakları ve Bilimsel Gelişme",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_BIY",
    name: "AYT Biyoloji",
    level: "AYT",
    tracks: ["SAYISAL"],
    order: 34,
    topics: [
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi",
      "Genden Proteine",
      "Canlılarda Enerji Dönüşümleri",
      "Bitki Biyolojisi",
      "Komünite ve Popülasyon",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_EDB",
    name: "AYT Türk Dili ve Edebiyatı",
    level: "AYT",
    tracks: ["EA", "SOZEL", "DIL"],
    order: 35,
    topics: [
      "Güzel Sanatlar ve Edebiyat",
      "Metinlerin Sınıflandırılması",
      "Şiir Bilgisi",
      "Edebi Sanatlar",
      "İslamiyet Öncesi Türk Edebiyatı",
      "Geçiş Dönemi",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Tanzimat Dönemi",
      "Servet-i Fünun ve Fecr-i Ati",
      "Milli Edebiyat",
      "Cumhuriyet Dönemi",
      "Roman - Hikâye - Tiyatro",
      "Dünya Edebiyatı",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_TAR",
    name: "AYT Tarih",
    level: "AYT",
    tracks: ["EA", "SOZEL"],
    order: 36,
    topics: [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ'da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyeti Kabulü",
      "Yerleşme ve Devletleşme Sürecinde Osmanlı",
      "Değişen Dünya Dengeleri",
      "Uluslararası İlişkiler",
      "Demokratikleşme Çabaları",
      "20. Yüzyıl Başlarında Osmanlı",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
      "II. Dünya Savaşı Sonrası Dünya",
      "Türkiye'nin Çağdaşlaşma Süreci",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_COG",
    name: "AYT Coğrafya",
    level: "AYT",
    tracks: ["EA", "SOZEL"],
    order: 37,
    topics: [
      "Ekosistem",
      "Nüfus Politikaları",
      "Şehir ve Fonksiyonları",
      "Türkiye Ekonomisi",
      "Ekonomi Politikaları",
      "Uluslararası Ulaşım Hatları",
      "Çevre ve Toplum",
      "Bölgesel Kalkınma",
      "Küresel Ortam",
      "Ülkeler Arası Etkileşim",
      "Doğal Afetler",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "AYT_FEL",
    name: "AYT Felsefe Grubu",
    level: "AYT",
    tracks: ["EA", "SOZEL"],
    order: 38,
    topics: [
      "Psikoloji - Bilim Olma Süreci",
      "Psikolojinin Temel Süreçleri",
      "Öğrenme - Bellek - Düşünme",
      "Kişilik ve Ruh Sağlığı",
      "Sosyoloji - Birey ve Toplum",
      "Toplumsal Yapı - Kurumlar",
      "Toplumsal Değişme",
      "Mantık - Klasik Mantık",
      "Sembolik Mantık",
      "İlk Çağ Felsefesi",
      "Orta Çağ Felsefesi",
      "Rönesans Felsefesi",
      "17. - 18. Yüzyıl Felsefesi",
      "19. - 20. Yüzyıl Felsefesi",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
  {
    code: "YDT_ING",
    name: "YDT İngilizce",
    level: "AYT",
    tracks: ["DIL"],
    order: 40,
    topics: [
      "Tenses",
      "Modals",
      "Passive Voice",
      "Relative Clauses",
      "Conditionals",
      "Reported Speech",
      "Prepositions",
      "Phrasal Verbs",
      "Vocabulary",
      "Cloze Test",
      "Restatement",
      "Sentence Completion",
      "Paragraph Completion",
      "Irrelevant Sentence",
      "Reading Comprehension",
      "Translation",
      "Dialogue Completion",
    ].map((name, i) => ({ name, level: "AYT", order: i })),
  },
];
